name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make dependences

    - name: Proyecto SMX
      run: make proyecto-smx	

    - name: Proyecto DAW
      run: make proyecto-daw	

    - name: Proyecto DAM
      run: make proyecto-dam	
      
    - name: Proyecto ASIR
      run: make proyecto-asir
      
    - uses: actions/upload-artifact@v4
      with:
        name: PCCFs
        path: PDFS/ #

    - name: Upload PCCF-DAW
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: PDFS/PCCF_SENIA_DAW.pdf
        asset_name: PCCF_SENIA_DAW.pdf
        asset_content_type: application/pdf
